src/Entity/Orders.php
<?php

namespace App\Entity;

use App\Repository\OrdersRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrdersRepository::class)]
class Orders
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $player_id = null;

    #[ORM\Column]
    protected ?int $team_id = null;

    #[ORM\Column]
    protected ?int $interested_team = null;

    #[ORM\Column]
    protected ?float $offer_amount = null;

    #[ORM\Column]
    private ?bool $status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPlayerId(): ?int
    {
        return $this->player_id;
    }

    public function setPlayerId(int $player_id): self
    {
        $this->player_id = $player_id;

        return $this;
    }

    public function getTeamId(): ?int
    {
        return $this->team_id;
    }

    public function setTeamId(int $team_id): self
    {
        $this->team_id = $team_id;

        return $this;
    }

    public function getInterestedTeam(): ?int
    {
        return $this->interested_team;
    }

    public function setInterestedTeam(int $interested_team): self
    {
        $this->interested_team = $interested_team;

        return $this;
    }

    public function getOfferAmount(): ?float
    {
        return $this->offer_amount;
    }

    public function setOfferAmount(float $offer_amount): self
    {
        $this->offer_amount = $offer_amount;

        return $this;
    }

    public function isStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }
}

src/Entity/Players.php
<?php

namespace App\Entity;

use App\Repository\PlayersRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PlayersRepository::class)]
class Players
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $firstName = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $lastName = null;

    #[ORM\Column]
    private ?int $team_id = null;

    #[ORM\Column]
    #[Assert\NotBlank]
    private ?float $market_value = null;

    #[ORM\Column(length: 2000, nullable: true)]
    private ?string $photo = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getTeamId(): ?int
    {
        return $this->team_id;
    }

    public function setTeamId(int $team_id): self
    {
        $this->team_id = $team_id;

        return $this;
    }

    public function getMarketValue(): ?float
    {
        return $this->market_value;
    }

    public function setMarketValue(float $market_value): self
    {
        $this->market_value = $market_value;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Controller/MarketController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Players;
use App\Entity\Orders;
use App\Entity\Teams;
use Knp\Component\Pager\PaginatorInterface;
use Doctrine\Persistence\ManagerRegistry;

class MarketController extends AbstractController
{
  private $doctrine;
  private $paginator;
  public function __construct(ManagerRegistry $doctrine, PaginatorInterface $paginator,)
  {
    $this->doctrine = $doctrine;
    $this->paginator = $paginator;
  }

  #[Route('/market-place', name: 'app_market_place')]
  public function market(Request $request): Response
  {
    $playerQuery = $this->doctrine->getManager()->getRepository(Players::class)
      ->findAllTeam();
    $pagination = $this->paginator->paginate(
      $playerQuery, /* query NOT result */
      $request->query->getInt('page', 1), /*page number*/
      6 /*limit per page*/
    );
    return $this->render('market/index.html.twig', [
      'error'         => '',
      'players' => $pagination
    ]);
  }

  #[Route('/order/{id}', name: 'app_place_order')]
  public function placeOrder(Request $request, int $id): Response
  {
    $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
    $error='';
    $playerQuery = $this->doctrine->getManager()->getRepository(Players::class)
      ->findOneJoinTeam($id);
    if (isset($_POST['submit'])) {
    if($this->getUser()->getTeamId()===$playerQuery[0]->getTeamId()){
      $error="You cannot buy this player because it exist within your team";

    }else{
      $entityManager = $this->doctrine->getManager();
      $player = new Orders();
      $player->setPlayerId($id);
      $player->setTeamId($playerQuery[0]->getTeamId());
      $player->setInterestedTeam($this->getUser()->getTeamId());
      $player->setOfferAmount(is_numeric($request->request->get('_offerAmount')) ? $request->request->get('_offerAmount') : 0);
      $player->setStatus(1);
      $entityManager->persist($player);
      $entityManager->flush();
      return $this->redirectToRoute('app_my_order');
    }
    }
    return $this->render('market/order.html.twig', [
      'error'         => '',
      'err'         => $error,
      'player' => $playerQuery,
      'moneyBalance' =>  $this->doctrine->getManager()->getRepository(Teams::class)->find($this->getUser()->getTeamId())->getBalance()
    ]);
  }

  #[Route('/my-order', name: 'app_my_order')]
  public function myOrder(Request $request, ManagerRegistry $doctrine): Response
  {
    $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
    $awaitingPurchaseOrder = $this->doctrine->getManager()->getRepository(Orders::class)
      ->findByInterestTeam($this->getUser()->getTeamId());
    $awaitingSalesOrder = $this->doctrine->getManager()->getRepository(Orders::class)
      ->findByTeam($this->getUser()->getTeamId());
    $entityManager = $doctrine->getManager();
    if (isset($_POST['submit'])) {
      $playerOrder = $this->doctrine->getRepository(Orders::class)->find($request->request->get('id'));
      $team_id = $playerOrder->getTeamId();
      $sellerAccount = $this->doctrine->getRepository(Teams::class)->find(2);
      $sellerAccount->setBalance($sellerAccount->getBalance() + $playerOrder->getOfferAmount());
      $entityManager->persist($sellerAccount);
      $entityManager->flush();
      $buyAccount = $this->doctrine->getRepository(Teams::class)->find($playerOrder->getInterestedTeam());
      $buyAccount->setBalance($buyAccount->getBalance() - $playerOrder->getOfferAmount());
      $entityManager->persist($buyAccount);
      $entityManager->flush();

      $entityManager->getRepository(Orders::class)->UpdateSales($playerOrder->getPlayerId(), $playerOrder->getInterestedTeam());

      return $this->redirectToRoute('app_my_order');
    }

    if (isset($_POST['delete'])) {
      $player = $entityManager->getRepository(Orders::class)->find($request->request->get('id'));
      if (!$player) {
        throw $this->createNotFoundException(
          'No article found for id ' . $request->request->get('id')
        );
      }
      $entityManager->remove($player);
      $entityManager->flush();
      return $this->redirectToRoute('app_my_order');
    }

    return $this->render('market/buyer_order.html.twig', [
      'error'         => '',
      'awaitingPurchaseOrder' => $awaitingPurchaseOrder,
      'awaitingSalesOrder' => $awaitingSalesOrder
    ]);
  }
}

templates/market/buyer_order.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<style>
    .example-wrapper {
        margin: 1em auto;
        max-width: 800px;
        width: 95%;
        font: 18px/1.5 sans-serif;
    }

    .example-wrapper code {
        background: #F5F5F5;
        padding: 2px 6px;
    }
</style>

<div class="example-wrapper">
    <section data-bs-version="5.1" class="form6 cid-tjttyxMM3T" id="form6-o">
        <div class="container">
            <div class="card-body">
                <h1> Purchasing Orders
            </div>
            <div class="table-responsive">
                <table class="table table-hover table-center mb-0">
                    <thead>
                        <tr>
                            <th rowspan="1">S/N</th>
                            <th rowspan="1">Player</th>
                            <th rowspan="1">Current team</th>
                            <th rowspan="1">Market worth </th>
                            <th rowspan="1">Amount Bid</th>
                            <th rowspan="1">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for player in awaitingPurchaseOrder %}
                        <tr>
                            <td>
                                1
                            </td>
                            <td>
                                {{ player.firstName }} {{ player.lastName }}
                            </td>
                            <td>
                                {{ player.name }}
                            </td>
                            <td>
                                {{ player.market_value|number_format(2, '.', ',') }}
                            </td>
                            <td>
                                {{ player[0].offerAmount|number_format(2, '.', ',') }}
                            </td>
                            <td>
                                <form method="post">
                                    <input type="hidden" name="id" value="{{ player[0].id }}">
                                    <button type="submit" name="delete" class="btn btn-danger display-4">Cancel
                                        order</button>
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <br>
            <br>
            <br>
            <hr>
            <h1> Orders from Interested Buyers
        </div>
        <div class="table-responsive">
            <table class="table table-hover table-center mb-0">
                <thead>
                    <tr>
                        <th rowspan="1">S/N</th>
                        <th rowspan="1">Player</th>
                        <th rowspan="1">Prospective buyer team</th>
                        <th rowspan="1">Market worth </th>
                        <th rowspan="1">Amount Bid</th>
                        <th rowspan="1">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for player in awaitingSalesOrder %}
                    <tr>
                        <td>
                            1
                        </td>
                        <td>
                            {{ player.firstName }} {{ player.lastName }}
                        </td>
                        <td>
                            {{ player.name }}
                        </td>
                        <td>
                            {{ player.market_value|number_format(2, '.', ',') }}
                        </td>
                        <td>
                            {{ player[0].offerAmount|number_format(2, '.', ',') }}
                        </td>
                        <td>
                            <form method="post">
                                <input type="hidden" name="id" value="{{ player[0].id }}">
                                <button type="submit" name="submit" class="btn btn-success display-4">Sell Now</button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

</div>
</div>

</div>
</section>





{% endblock %}

templates/market/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<style>
    .example-wrapper {
        margin: 1em auto;
        max-width: 800px;
        width: 95%;
        font: 18px/1.5 sans-serif;
    }

    .example-wrapper code {
        background: #F5F5F5;
        padding: 2px 6px;
    }
</style>

<div class="example-wrapper">
    <section data-bs-version="5.1" class="form6 cid-tjttyxMM3T" id="form6-o">
        <div class="container">
            <div class="mbr-section-head">

                <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                    <strong>Market Place</strong>
                </h3>

            </div>

            <div class="row mt-4">
                {% for player in players %}
                <div class="item features-image сol-12 col-md-6 col-lg-6">
                    <div class="item-wrapper">
                        <div class="item-img">
                            <img src="{{ player[0].photo }}" alt="Mobirise Website Builder" title="">
                        </div>
                        <div class="item-content">
                            <h5 class="item-title mbr-fonts-style"><a href="#top" class="text-primary"></a></h5>
                            <h6 class="item-subtitle mbr-fonts-style mt-1 display-7"><strong>{{ player[0].lastName }}
                                </strong><em>{{ player[0].firstName }}</em></h6>
                            <h6 class="item-subtitle mbr-fonts-style mt-1 display-7"><strong>Team
                                </strong><em>{{ player.name }}</em></h6>
                            <p class="mbr-text mbr-fonts-style mt-3 display-7">Market
                                Worth:{{ player[0].marketValue|number_format(2, '.', ',') }}
                            </p>
                        </div>


                        <div class="mbr-section-btn item-footer mt-2">
                            <a href="/order/{{ player[0].id }}" class="btn btn-info item-btn display-7">Buy Now</a>
                        </div>

                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>
    <div class="pagination">
        {{ knp_pagination_render(players) }}
    </div>
</div>

{% endblock %}

templates/market/order.html.twig
{% extends 'base2.html.twig' %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
 <section data-bs-version="5.1" class="form6 cid-tjttyxMM3T" id="form6-o">
    <div class="container">
       
        <div class="row justify-content-center mt-4">
            <div class="col-lg-8 mx-auto mbr-form" data-form-type="formoid">
             <div class="item features-image сol-12 col-md-6 col-lg-6">
            <div class="item-wrapper">
                <div class="item-img">
                    <img src="{{ player[0].photo }}" alt="Mobirise Website Builder" title="">
                </div>
                <div class="item-content">
                    <h5 class="item-title mbr-fonts-style"><a href="#top" class="text-primary"></a></h5>
                    <h6 class="item-subtitle mbr-fonts-style mt-1 display-7"><strong>{{player[0].lastName}}
                        </strong><em>{{player[0].firstName}}</em></h6>
                        <h6 class="item-subtitle mbr-fonts-style mt-1 display-7"><strong>Team:
                        </strong><em>{{player.name}}</em></h6>
                    <p class="mbr-text mbr-fonts-style mt-3 display-7">Market Worth:{{ player[0].marketValue|number_format(2, '.', ',')  }}</p>
                </div> 
            </div>
        </div>
                <form   method="post" class="mbr-form form-with-styler mx-auto" data-form-title="Form Name"><input type="hidden" name="email" data-form-email="true" value="GZ5nNSxJlux3pEFZnFhkm1EMBIsz2c00ZhX9JIudaNNz+X2F4HQ40MrCNoihoVL4dPe1CF/Gz2Ht7RA29Ma5VxwJxwDD3rP3T5kdWCY+wN1BSgF0wKfG1t8aRaD0qfT5">
                    <div class="row">
                        <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
                        <div hidden="hidden" data-form-alert="" class="alert alert-success col-12">Thanks for filling out the form!</div>
                         {% if error %}
                            <div data-form-alert-danger="" class="alert alert-danger col-12">
                                Oops...! some problem! {{ error.messageKey|trans(error.messageData, 'security') }}
                            </div>
                        {% endif %}
                        {% if err %}
                            <div data-form-alert-danger="" class="alert alert-danger col-12">
                                {{ err }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="dragArea row">
                        <div class="col-lg-12 col-md-12 col-sm-12 form-group mb-3" data-for="offerAmount">
                            <input type="text" id="offerAmount" name="_offerAmount" placeholder="Bid Amount eg 300,000"  class="form-control" >
                        </div>
                         
                        <div >
                            <button type="submit"  name="submit" class="btn btn-primary">Submit</button>
                            <a class="btn btn-warning" href="{{ path('app_market_place') }}">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <br>
        <h2>Money Balance: {{moneyBalance|number_format(2, '.', ',')}}</h2>
    </div>
</section>  
</div>

{% endblock %}